/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFRAMES;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author TheLokestraps
 */
public class Circulacion extends javax.swing.JFrame {

    /**
     * Creates new form Circulacion
     */
    public Circulacion() {
        initComponents();
        
        jPanel1.setBackground(new Color(45,22,0,69));

        
        ImageIcon LaImg = new ImageIcon("src\\Imagenes2D\\1543588021_056671_1543588194_noticia_normal.jpg");
        ImageIcon Resize = new ImageIcon(LaImg.getImage().getScaledInstance(Background.getWidth(),Background.getHeight(),Image.SCALE_SMOOTH));
        this.Background.setIcon(Resize);
        
        ImageIcon BUS1 = new ImageIcon("src\\Imagenes2D\\bus01.png");
        ImageIcon Resize1 = new ImageIcon(BUS1.getImage().getScaledInstance(Anim.getWidth(),Anim.getHeight(),Image.SCALE_DEFAULT));
        this.Anim.setIcon(Resize1);
        
        ImageIcon BUS2 = new ImageIcon("src\\Imagenes2D\\bus02.png");
        ImageIcon Resize2 = new ImageIcon(BUS2.getImage().getScaledInstance(Anim.getWidth(),Anim.getHeight(),Image.SCALE_DEFAULT));
        
        ImageIcon BUS3 = new ImageIcon("src\\Imagenes2D\\bus03.png");
        ImageIcon Resize3 = new ImageIcon(BUS3.getImage().getScaledInstance(Anim.getWidth(),Anim.getHeight(),Image.SCALE_DEFAULT));
        
        ImageIcon BUS4 = new ImageIcon("src\\Imagenes2D\\bus04.png");
        ImageIcon Resize4 = new ImageIcon(BUS4.getImage().getScaledInstance(Anim.getWidth(),Anim.getHeight(),Image.SCALE_DEFAULT));
        
         ImageIcon Golazo = new ImageIcon("src\\Imagenes2D\\images.png");
        ImageIcon Resize5 = new ImageIcon(Golazo.getImage().getScaledInstance(goal.getWidth(),goal.getHeight(),Image.SCALE_DEFAULT));
        goal.setIcon(Resize5);
        
    }
   
    
        private class TransparentPanel extends JPanel {
        {
            setOpaque(false);
        }
        public void paintComponent(Graphics g) {
            g.setColor(getBackground());
            Rectangle r = g.getClipBounds();
            g.fillRect(r.x, r.y, r.width, r.height);
            super.paintComponent(g);
        }
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Anim = new javax.swing.JLabel();
        goal = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        Anim.setText("Animation");
        jPanel1.add(Anim);
        Anim.setBounds(20, 30, 110, 70);

        goal.setText("Llegada");
        jPanel1.add(goal);
        goal.setBounds(563, 27, 100, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 110, 680, 120);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes2D/1543588021_056671_1543588194_noticia_normal.jpg"))); // NOI18N
        Background.setText("dadsad");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 810, 600);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 270, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Circulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Circulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Circulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Circulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Circulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anim;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel goal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
